In [1]:
import sys
sys.path.append('../bggcomplex')

from bggcomplex import BGGComplex
from fast_module import FastLieAlgebraCompositeModule, FastModuleFactory, BGGCohomology
from tqdm.auto import tqdm
from compute_maps import BGGMapSolver
import numpy as np

Let's first fix the problem with compute maps. This should make it a bit easier to diagnose the problems with the diff computation. 

In [2]:
%%prun
d='F4'
BGG = BGGComplex(d)
factory = FastModuleFactory(BGG.LA)
component_dic = {'u':factory.build_component('u','coad',subset=[1,2,4])}
u_dim = len(component_dic['u'].basis)
print('dim of u is %d for root system %s' % (u_dim, d))

pbar1 = tqdm(range(u_dim+1))
pbar2 = tqdm()
pbar3 = tqdm()
for k in pbar1:
    components = [[('u',k,'wedge')]]
    module = FastLieAlgebraCompositeModule(factory,components,component_dic)

    cohom = BGGCohomology(BGG, module,pbars=[pbar2,pbar3])

    cohom.cohomology_LaTeX(complex_string=r'X_{'+d+r'},\wedge^{'+str(k)+'}T_X')#,i=1)

dim of u is 20 for root system F4


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

KeyboardInterrupt: 

In [14]:
d='F4'
BGG = BGGComplex(d)

In [28]:
mu = (3,6,9,6)
mu_alpha = BGG.weight_to_alpha_sum(BGG._tuple_to_weight(mu))
solver = BGGMapSolver(BGG, mu_alpha)

In [68]:
pbw = solver.partition_to_PBW((17, 16))
pbw

PBW[-alpha[1] - 2*alpha[2] - 2*alpha[3] - alpha[4]]*PBW[-alpha[1] - alpha[2] - 2*alpha[3] - 2*alpha[4]]

In [69]:
a1 = list(pbw)[0][0].leading_support()
display(a1)
a2 = list(pbw)[0][0].trailing_support()
a2

-alpha[1] - 2*alpha[2] - 2*alpha[3] - alpha[4]

-alpha[1] - alpha[2] - 2*alpha[3] - 2*alpha[4]

In [70]:
BGG.PBW._basis_key(a1)

44

In [71]:
BGG.PBW._basis_key(a2)

45

In [80]:
lie_alg_order = {k:i for i,k in enumerate(BGG.LA.basis().keys())}
ordered_roots = sorted([BGG.weight_to_alpha_sum(r) for r in BGG.domain.negative_roots()],key=lambda r: lie_alg_order[r])
[-BGG.alpha_sum_to_array(r) for r in ordered_roots]

[array([0, 0, 0, 1]),
 array([0, 0, 1, 0]),
 array([0, 1, 0, 0]),
 array([1, 0, 0, 0]),
 array([0, 0, 1, 1]),
 array([0, 1, 1, 0]),
 array([1, 1, 0, 0]),
 array([0, 1, 1, 1]),
 array([0, 1, 2, 0]),
 array([1, 1, 1, 0]),
 array([0, 1, 2, 1]),
 array([1, 1, 1, 1]),
 array([1, 1, 2, 0]),
 array([0, 1, 2, 2]),
 array([1, 2, 2, 0]),
 array([1, 1, 2, 1]),
 array([1, 2, 2, 1]),
 array([1, 1, 2, 2]),
 array([1, 2, 3, 1]),
 array([1, 2, 2, 2]),
 array([1, 2, 3, 2]),
 array([1, 2, 4, 2]),
 array([1, 3, 4, 2]),
 array([2, 3, 4, 2])]

In [81]:
BGG.neg_roots

[array([0, 0, 0, 1]),
 array([0, 0, 1, 0]),
 array([0, 1, 0, 0]),
 array([1, 0, 0, 0]),
 array([0, 0, 1, 1]),
 array([0, 1, 1, 0]),
 array([1, 1, 0, 0]),
 array([0, 1, 1, 1]),
 array([0, 1, 2, 0]),
 array([1, 1, 1, 0]),
 array([0, 1, 2, 1]),
 array([1, 1, 1, 1]),
 array([1, 1, 2, 0]),
 array([0, 1, 2, 2]),
 array([1, 1, 2, 1]),
 array([1, 2, 2, 0]),
 array([1, 1, 2, 2]),
 array([1, 2, 2, 1]),
 array([1, 2, 2, 2]),
 array([1, 2, 3, 1]),
 array([1, 2, 3, 2]),
 array([1, 2, 4, 2]),
 array([1, 3, 4, 2]),
 array([2, 3, 4, 2])]

In [16]:
list(enumerate(BGG.neg_roots))

[(0, array([0, 0, 0, 1])),
 (1, array([0, 0, 1, 0])),
 (2, array([0, 1, 0, 0])),
 (3, array([1, 0, 0, 0])),
 (4, array([0, 0, 1, 1])),
 (5, array([0, 1, 1, 0])),
 (6, array([1, 1, 0, 0])),
 (7, array([0, 1, 1, 1])),
 (8, array([0, 1, 2, 0])),
 (9, array([1, 1, 1, 0])),
 (10, array([0, 1, 2, 1])),
 (11, array([1, 1, 1, 1])),
 (12, array([1, 1, 2, 0])),
 (13, array([0, 1, 2, 2])),
 (14, array([1, 1, 2, 1])),
 (15, array([1, 2, 2, 0])),
 (16, array([1, 1, 2, 2])),
 (17, array([1, 2, 2, 1])),
 (18, array([1, 2, 2, 2])),
 (19, array([1, 2, 3, 1])),
 (20, array([1, 2, 3, 2])),
 (21, array([1, 2, 4, 2])),
 (22, array([1, 3, 4, 2])),
 (23, array([2, 3, 4, 2]))]

In [58]:
BGG = BGGComplex('F4')
sorted_alphas = sorted([BGG.weight_to_alpha_sum(r) for r in BGG.domain.negative_roots()])
list(enumerate(sorted_alphas))

[(0, -2*alpha[1] - 3*alpha[2] - 4*alpha[3] - 2*alpha[4]),
 (1, -alpha[1]),
 (2, -alpha[1] - 3*alpha[2] - 4*alpha[3] - 2*alpha[4]),
 (3, -alpha[1] - 2*alpha[2] - 4*alpha[3] - 2*alpha[4]),
 (4, -alpha[1] - 2*alpha[2] - 3*alpha[3] - 2*alpha[4]),
 (5, -alpha[1] - 2*alpha[2] - 3*alpha[3] - alpha[4]),
 (6, -alpha[1] - 2*alpha[2] - 2*alpha[3]),
 (7, -alpha[1] - 2*alpha[2] - 2*alpha[3] - 2*alpha[4]),
 (8, -alpha[1] - 2*alpha[2] - 2*alpha[3] - alpha[4]),
 (9, -alpha[1] - alpha[2]),
 (10, -alpha[1] - alpha[2] - 2*alpha[3]),
 (11, -alpha[1] - alpha[2] - 2*alpha[3] - 2*alpha[4]),
 (12, -alpha[1] - alpha[2] - 2*alpha[3] - alpha[4]),
 (13, -alpha[1] - alpha[2] - alpha[3]),
 (14, -alpha[1] - alpha[2] - alpha[3] - alpha[4]),
 (15, -alpha[2]),
 (16, -alpha[2] - 2*alpha[3]),
 (17, -alpha[2] - 2*alpha[3] - 2*alpha[4]),
 (18, -alpha[2] - 2*alpha[3] - alpha[4]),
 (19, -alpha[2] - alpha[3]),
 (20, -alpha[2] - alpha[3] - alpha[4]),
 (21, -alpha[3]),
 (22, -alpha[3] - alpha[4]),
 (23, -alpha[4])]

In [56]:
sorted_alphas[15]<sorted_alphas[9]

False