In [24]:
import sys
sys.path.append('../bggcomplex')

from bggcomplex import BGGComplex
from fast_module import FastLieAlgebraCompositeModule, FastModuleFactory, BGGCohomology, WeightSet
import cohomology
import numpy as np

In [25]:
BGG = BGGComplex('G2')
factory = FastModuleFactory(BGG.LA)

component_dic = {'b':factory.build_component('g','coad',subset=[])}

In [26]:
components1 = [[("b",2,'wedge')]]
module1 = FastLieAlgebraCompositeModule(factory,components1,component_dic)

components2 = [[("b",1,'wedge')]*2]
module2 = FastLieAlgebraCompositeModule(factory,components2,component_dic)

components3 = [[("b",2,'sym')]]
module3 = FastLieAlgebraCompositeModule(factory,components3,component_dic)

module2.weight_components;

In [27]:
from sympy.utilities.iterables import multiset_permutations
from sympy.combinatorics.permutations import Permutation
T = dict()
for mu in module1.weight_components.keys():
    comp = module1.weight_components[mu][0][1]
    sparse_mat = dict()
    for wedge_index, wedge_row in enumerate(comp):
        perms = list(multiset_permutations(wedge_row))
        perms_standard = list(multiset_permutations(range(len(wedge_row))))
        signs = [Permutation(p).signature() for p in perms_standard]
        perm_dic={tuple(p):s for p,s in zip(perms,signs)}


        comp2 = module2.weight_components[mu][0][1]
        for j,row in enumerate(comp2):
            if tuple(row) in perm_dic:
                sparse_mat[(wedge_index,j)]= perm_dic[tuple(row)]
    M = matrix(ZZ,sparse_mat,nrows = len(comp), ncols = len(comp2), sparse=True)
    T[mu]=M.transpose().kernel().basis_matrix()
T

{(-6, -3): [1 1],
 (-5, -3): [1 1],
 (-5, -2): [1 1],
 (-4, -3): [1 1],
 (-4, -2): [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0],
 (-4, -1): [1 1],
 (-3, -3): [1 1],
 (-3, -2): [1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 1 0 0]
 [0 0 0 1 1 0 0 0],
 (-3, -1): [1 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0]
 [0 0 1 0 0 0 1 0]
 [0 0 0 1 1 0 0 0],
 (-3, 0): [1 1],
 (-2, -2): [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0],
 (-2, -1): [1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0],
 (-2, 0): [1 0 0 1 0]
 [0 1 0 0 1]
 [0 0 1 0 0],
 (-1, -2): [1 1],
 (-1, -1): [1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0],
 (-1, 0): [1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 1 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0],
 (-1, 1): [1 1],
 (0, -1): [1 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0 0],
 (0, 0): [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0

In [28]:
cohom = BGGCohomology(BGG, module2, coker=T)
cohom.cohomology_LaTeX()

<IPython.core.display.Math object>

In [29]:
cohom = BGGCohomology(BGG, module3)
cohom.cohomology_LaTeX()

<IPython.core.display.Math object>

## Quantum center