In [1]:
import sys
sys.path.append('../bggcomplex')

from bggcomplex import BGGComplex
from fast_module import FastLieAlgebraCompositeModule, FastModuleFactory, BGGCohomology, WeightSet
import cohomology
import numpy as np

In [2]:
BGG = BGGComplex('A2')
factory = FastModuleFactory(BGG.LA)

component_dic = {'b':factory.build_component('u','coad',subset=[])}

In [3]:
components1 = [[("b",3,'wedge')]]
module1 = FastLieAlgebraCompositeModule(factory,components1,component_dic)

components2 = [[("b",1,'wedge')]*3]
module2 = FastLieAlgebraCompositeModule(factory,components2,component_dic)

module2.weight_components

{(0, 3): [(0, array([[6, 6, 6]], dtype=int32))], (1, 2): [(0, array([[6, 6, 7],
          [6, 7, 6],
          [7, 6, 6]], dtype=int32))], (1, 3): [(0, array([[5, 6, 6],
          [6, 5, 6],
          [6, 6, 5]], dtype=int32))], (2, 1): [(0, array([[6, 7, 7],
          [7, 6, 7],
          [7, 7, 6]], dtype=int32))], (2, 2): [(0, array([[5, 6, 7],
          [5, 7, 6],
          [6, 5, 7],
          [6, 7, 5],
          [7, 5, 6],
          [7, 6, 5]], dtype=int32))], (2, 3): [(0, array([[5, 5, 6],
          [5, 6, 5],
          [6, 5, 5]], dtype=int32))], (3,
  0): [(0, array([[7, 7, 7]], dtype=int32))], (3, 1): [(0, array([[5, 7, 7],
          [7, 5, 7],
          [7, 7, 5]], dtype=int32))], (3, 2): [(0, array([[5, 5, 7],
          [5, 7, 5],
          [7, 5, 5]], dtype=int32))], (3,
  3): [(0, array([[5, 5, 5]], dtype=int32))]}

In [4]:
from sympy.utilities.iterables import multiset_permutations
from sympy.combinatorics.permutations import Permutation
T = dict()
for mu in module1.weight_components.keys():
    comp = module1.weight_components[mu][0][1]
    sparse_mat = dict()
    for wedge_index, wedge_row in enumerate(comp):
        perms = list(multiset_permutations(wedge_row))
        perms_standard = list(multiset_permutations(range(len(wedge_row))))
        signs = [Permutation(p).signature() for p in perms_standard]
        perm_dic={tuple(p):s for p,s in zip(perms,signs)}


        comp2 = module2.weight_components[mu][0][1]
        for j,row in enumerate(comp2):
            if tuple(row) in perm_dic:
                sparse_mat[(wedge_index,j)]= perm_dic[tuple(row)]
    M = matrix(ZZ,sparse_mat,nrows = len(comp), ncols = len(comp2), sparse=True)
    T[mu]=M.transpose().kernel().basis_matrix()
T

{(2, 2): [ 1  0  0  0  0  1]
 [ 0  1  0  0  0 -1]
 [ 0  0  1  0  0 -1]
 [ 0  0  0  1  0  1]
 [ 0  0  0  0  1  1]}

In [5]:
module1.weight_components

{(2, 2): [(0, array([[5, 6, 7]], dtype=int32))]}

In [9]:
cohom = BGGCohomology(BGG, module2,coker=T)

In [10]:
cohom.cohomology_LaTeX(print_betti=False)

<IPython.core.display.Math object>

## Quantum center