In [1]:
import sys
sys.path.append('../bggcomplex')

from bggcomplex import BGGComplex
from fast_module import FastLieAlgebraCompositeModule, FastModuleFactory, BGGCohomology, WeightSet
import cohomology
import numpy as np

In [2]:
BGG = BGGComplex('B2')
factory = FastModuleFactory(BGG.LA)

component_dic = {'b':factory.build_component('b','coad',subset=[]),'g':factory.build_component('g','coad',subset=[])
                ,'u':factory.build_component('u','coad',subset=[]),'n':factory.build_component('n','coad',subset=[])}

components = [[('u', 2, 'sym'), ('n', 3, 'wedge')],
 [('u', 1, 'sym'), ('g', 1, 'wedge'), ('n', 2, 'wedge')]]
module = FastLieAlgebraCompositeModule(factory,components,component_dic)
cohom = BGGCohomology(BGG, module)
cohom.cohomology_LaTeX()

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [3]:
BGG = BGGComplex('B2')
factory = FastModuleFactory(BGG.LA)


component_dic = {'b':factory.build_component('g','coad',subset=[])}

components = [[('b',2,'wedge')],[('b',2,'sym')]]
module = FastLieAlgebraCompositeModule(factory,components,component_dic)
cohom = BGGCohomology(BGG, module)
cohom.cohomology_LaTeX()
print('-'*10)

components = [[('b',1,'wedge')]*2]*2
module = FastLieAlgebraCompositeModule(factory,components,component_dic)
cohom = BGGCohomology(BGG, module)
cohom.cohomology_LaTeX()

<IPython.core.display.Math object>

----------


<IPython.core.display.Math object>

In [4]:
BGG = BGGComplex('G2')
factory = FastModuleFactory(BGG.LA)

component_dic = {'b':factory.build_component('g','coad',subset=[])}

In [5]:
components1 = [[("b",2,'wedge')]]
module1 = FastLieAlgebraCompositeModule(factory,components1,component_dic)

components2 = [[("b",1,'wedge')]*2]*2
module2 = FastLieAlgebraCompositeModule(factory,components2,component_dic)

components3 = [[("b",2,'sym')]]
module3 = FastLieAlgebraCompositeModule(factory,components3,component_dic)

module2.weight_components;

In [6]:
from sympy.utilities.iterables import multiset_permutations
from sympy.combinatorics.permutations import Permutation
T = dict()
for mu in module1.weight_components.keys():
    comp = module1.weight_components[mu][0][1]
    sparse_mat = dict()
    for wedge_index, wedge_row in enumerate(comp):
        perms = list(multiset_permutations(wedge_row))
        perms_standard = list(multiset_permutations(range(len(wedge_row))))
        signs = [Permutation(p).signature() for p in perms_standard]
        perm_dic={tuple(p):s for p,s in zip(perms,signs)}


        comp2 = module2.weight_components[mu][0][1]
        for j,row in enumerate(comp2):
            if tuple(row) in perm_dic:
                sparse_mat[(wedge_index,j)]= perm_dic[tuple(row)]
    M = matrix(ZZ,sparse_mat,nrows = len(comp), ncols = len(comp2), sparse=True)
    T[mu]=M.transpose().kernel().basis_matrix()
    L = np.array(T[mu])
    zero = np.zeros_like(L)
    T[mu] = Matrix(np.vstack([
        np.hstack([L,zero]),
        np.hstack([zero,L])
    ]))
T

{(-6, -3): [1 1 0 0]
 [0 0 1 1], (-5, -3): [1 1 0 0]
 [0 0 1 1], (-5, -2): [1 1 0 0]
 [0 0 1 1], (-4, -3): [1 1 0 0]
 [0 0 1 1], (-4, -2): [1 0 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0], (-4, -1): [1 1 0 0]
 [0 0 1 1], (-3, -3): [1 1 0 0]
 [0 0 1 1], (-3, -2): [1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0], (-3, -1): [1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0], (-3, 0): [1 1 0 0]
 [0 0 1 1], (-2, -2): [1 0 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 

In [7]:
cohom = BGGCohomology(BGG, module2, coker=T)
cohom.cohomology_LaTeX()

<IPython.core.display.Math object>

In [8]:
cohom = BGGCohomology(BGG, module3)
cohom.cohomology_LaTeX()

<IPython.core.display.Math object>

## Quantum center

In [9]:
len(factory.basis['u'])

6

In [15]:
s = 1
i = 0
j = 3
k = s-i-j

BGG = BGGComplex('A3')
def Mijk(BGG,i,j,k):
    factory = FastModuleFactory(BGG.LA)

    component_dic = {'b':factory.build_component('b','coad',subset=[]),'u':factory.build_component('u','coad',subset=[]),
                    'g':factory.build_component('g','coad',subset=[]),'n':factory.build_component('n','coad',subset=[])}
    
    dim_u = len(factory.basis['u'])
    dim_n = len(factory.basis['n'])
    dim_g = len(factory.g_basis)
    
    components = []
    for r in range(j+k//2+1):
        if (j-r<=dim_n):
            components.append([('u',j+k//2-r,'sym'),('g',r,'wedge'),('n',j-r,'wedge')])

    module = FastLieAlgebraCompositeModule(factory,components,component_dic)
    
    return module

In [16]:
def sort_sign(A):
    num_cols = A.shape[1]
    if num_cols>1:
        signs=(-1)**(sum([(A[:,0]<A[:,i]) for i in range(1,num_cols)])%2)
        mask=sum([(A[:,0]==A[:,i]) for i in range(1,num_cols)])==0
        return (np.sort(A),signs,mask)
    else:
        return (A,np.ones(len(A),dtype=int),np.ones(len(A),dtype=bool))
sort_sign(np.array([[3,3],[2,3],[3,3]]))

(array([[3, 3],
        [2, 3],
        [3, 3]]), array([ 1, -1,  1]), array([False,  True, False]))

right, but this completely disregards the presence of phi... it's not the direct sum of maps from g tensor stuff and u+n tensor stuff, but rather from b tensor stuff, under the map phi!

coker_dic = dict()
for r in range(j-1+k//2+1):
    coker_dic[r+1]=dict()
    num_u = j-1+k//2-r
    total_num = 2*j+k//2-r-1
    col_permution = range(1,num_u+1)+[0]+range(num_u+1,total_num)
    for mu,comp in module_g.weight_components.items():
        for comp_num, basis in comp:
            if comp_num==r:
                new_basis = basis[:,col_permution]
                g_sort, signs, mask = sort_sign(new_basis[:,num_u:num_u+1+r])
                new_basis[:,num_u:num_u+1+r] = g_sort
                new_basis = new_basis[mask]

                if len(new_basis)>0:
                    for m,b in module.weight_components[mu]:
                        if m == r+1:
                            target_dic = {tuple(row):i for i,row in enumerate(b)}
                            coker_dic[r+1][mu]= [(target_dic[tuple(row)],sign) 
                                                 for row, sign in zip(new_basis,signs) if sign!=0]

### def of phi

So we have $\phi\colon\mathfrak b\to \operatorname{End}(\mathfrak u)\cong \mathfrak n\otimes \mathfrak u$ given by the coadjoint action. We write this as a dict
>element of b -> [[element of n, element of u, coefficient],...] 

This then also gives the map $\mathfrak b\to \mathfrak g\oplus\mathfrak n\otimes\mathfrak u$

In [17]:
def compute_phi(BGG):
    factory = FastModuleFactory(BGG.LA)
    
    component_dic = {'u':factory.build_component('u','coad',subset=[])}
    components_phi = [[('u',1,'wedge')]]
    
    module_phi = FastLieAlgebraCompositeModule(factory,components_phi,component_dic)
    
    b_basis = factory.parabolic_p_basis(None)
    u_basis = factory.parabolic_u_basis(None)
    coad_dic = factory.coadjoint_action_tensor(b_basis,u_basis)
    
    phi_image = {b:[] for b in b_basis}
    for (b,u),n_dic in coad_dic.items():
        n,coeff = n_dic.items()[0]
        phi_image[b].append(np.array([factory.dual_root_dict[u],n,coeff]))
    
    for b in phi_image.keys():
        img = phi_image[b]
        if len(img)>0:
            phi_image[b]=np.vstack(img)
        else:
            phi_image[b]=[]
    return phi_image

In [18]:

def Tijk_basis(BGG,i,j,k):
    factory = FastModuleFactory(BGG.LA)
    wc_mod = Mijk(BGG,i,j,k)
    wc_rel = Mijk(BGG,i,j-1,k)
    
    coker_dic = dict()
    mu_source_counters = dict()
    
    phi_image = compute_phi(BGG)
    
    for mu, components in wc_rel.weight_components.items():

        for b, n_tensor_u in phi_image.items():
            new_mu = tuple(mu+factory.weight_dic[b])
            if new_mu not in mu_source_counters:
                mu_source_counters[new_mu]=0
            sparse_relations = []
            for comp_num, basis in components:
                r = wc_rel.components[comp_num][1][1]
                t_un_insert = None
                t_g_insert = None
                for c, comp_list in enumerate(wc_mod.components):
                    if comp_list[1][1] == r:
                        t_un_insert = c
                    if comp_list[1][1] == r+1:
                        t_g_insert = c

                num_rows = len(basis)
                num_u,num_g,num_n = (j-1+k//2-r,r,j-1-r)

                basis_enum = np.arange(mu_source_counters[new_mu],mu_source_counters[new_mu]+num_rows,dtype=int).reshape((-1,1))
                mu_source_counters[new_mu]+=num_rows


                # Insert g
                if t_g_insert is not None:
                    new_basis = np.hstack([basis_enum,basis[:,:num_u],b*np.ones(shape=(num_rows,1),dtype=int),basis[:,num_u:]])
                    sort_basis, signs, mask = sort_sign(new_basis[:,num_u+1:num_u+num_g+2])
                    new_basis[:,num_u+1:num_u+num_g+2] = sort_basis
                    new_basis = new_basis[mask]
                    basis_g = np.zeros(shape=(len(new_basis),3), dtype=int)
                    for row_num, (row, sign) in enumerate(zip(new_basis, signs[mask])):
                        source = row[0]

                        target = wc_mod.weight_comp_index_numbers[new_mu][tuple(list(row[1:])+[t_g_insert])]
                        basis_g[row_num] = [source,target,sign]
                    if len(basis_g)>0:
                        sparse_relations.append(basis_g)

                # Insert n_tensor_u
                if t_un_insert is not None:
                    for n,u,coeff in n_tensor_u:
                        n_column = n*np.ones(shape=(num_rows,1),dtype=int)
                        u_column = u*np.ones(shape=(num_rows,1),dtype=int)
                        new_basis = np.hstack([basis_enum,u_column,basis[:,:num_u+num_g],n_column,basis[:,num_u+num_g:]])
                        new_basis[:,1:num_u+2]=np.sort(new_basis[:,1:num_u+2])
                        sort_basis, signs, mask = sort_sign(new_basis[:,num_u+num_g+2:])
                        new_basis[:,num_u+num_g+2:]=sort_basis
                        signs=coeff*signs[mask]
                        new_basis = new_basis[mask]
                        basis_un = np.zeros(shape=(len(new_basis),3), dtype=int)
                        for row_num, (row, sign) in enumerate(zip(new_basis, signs)):
                            source = row[0]
                            target = wc_mod.weight_comp_index_numbers[new_mu][tuple(list(row[1:])+[t_un_insert])]
                            basis_un[row_num] = [source,target,sign]
                        if len(basis_un)>0:
                            sparse_relations.append(basis_un)
            if len(sparse_relations)>0:
                if new_mu not in coker_dic:
                    coker_dic[new_mu]=[]
                coker_dic[new_mu]+=sparse_relations
    coker_dic = {mu:cohomology.sort_merge(np.concatenate(rels)) for mu,rels in coker_dic.items()}

    T=dict()
    for mu,rels in coker_dic.items():
        source_dim = mu_source_counters[mu]
        target_dim = wc_mod.dimensions[mu]
        sparse_dic = dict()
        for source,target,coeff in rels:
            sparse_dic[(source,target)]=coeff

        M = matrix(ZZ,sparse_dic,nrows = source_dim, ncols = target_dim, sparse=True)
        T[mu]=M.transpose().kernel().basis_matrix()
    return T

problem in the algorithm:
the source basis of cohomology computation is still assumed to be that of direct sum decomposition, but this is not actually the case. 

solution:
we build two dictionaries. One sending an index + direct_sum_component_number to an index of the entire weight component.
The other sends a row+direct_sum_component_number to the index of the weight component. This dictionary is already used in two instances. 
Then we only do the direct sum source/target component shifting when there is no cokernel

Moreover the current method of using the maximum is not desirable either for `comp_offset_s`. If we have multiple arrows with same source, but different maximum indices at some particular step, then this might break stuff. Instead we need to take the dimension of the weight space as increment of the offset. 

In [19]:
Mijk(BGG,i,j,k).components[0][1][1]

0

In [20]:
display(Mijk(BGG,i,j,k).components)
display(Mijk(BGG,i,j-1,k).components)

[[('u', 2, 'sym'), ('g', 0, 'wedge'), ('n', 3, 'wedge')],
 [('u', 1, 'sym'), ('g', 1, 'wedge'), ('n', 2, 'wedge')],
 [('u', 0, 'sym'), ('g', 2, 'wedge'), ('n', 1, 'wedge')]]

[[('u', 1, 'sym'), ('g', 0, 'wedge'), ('n', 2, 'wedge')],
 [('u', 0, 'sym'), ('g', 1, 'wedge'), ('n', 1, 'wedge')]]

In [21]:
Mijk(BGG,i,j,k).dimensions

{(-3, -3, -2): 1,
 (-3, -3, -1): 2,
 (-3, -3, 0): 1,
 (-3, -2, -2): 2,
 (-3, -2, -1): 6,
 (-3, -2, 0): 5,
 (-3, -2, 1): 2,
 (-3, -1, -2): 1,
 (-3, -1, -1): 5,
 (-3, -1, 0): 7,
 (-3, -1, 1): 3,
 (-3, 0, -1): 2,
 (-3, 0, 0): 3,
 (-3, 0, 1): 2,
 (-2, -3, -3): 1,
 (-2, -3, -2): 6,
 (-2, -3, -1): 9,
 (-2, -3, 0): 6,
 (-2, -3, 1): 2,
 (-2, -2, -3): 2,
 (-2, -2, -2): 17,
 (-2, -2, -1): 34,
 (-2, -2, 0): 30,
 (-2, -2, 1): 9,
 (-2, -2, 2): 1,
 (-2, -1, -3): 1,
 (-2, -1, -2): 13,
 (-2, -1, -1): 42,
 (-2, -1, 0): 48,
 (-2, -1, 1): 20,
 (-2, -1, 2): 2,
 (-2, 0, -2): 5,
 (-2, 0, -1): 21,
 (-2, 0, 0): 34,
 (-2, 0, 1): 18,
 (-2, 0, 2): 3,
 (-2, 1, -2): 1,
 (-2, 1, -1): 4,
 (-2, 1, 0): 7,
 (-2, 1, 1): 5,
 (-2, 1, 2): 1,
 (-1, -3, -3): 2,
 (-1, -3, -2): 9,
 (-1, -3, -1): 13,
 (-1, -3, 0): 8,
 (-1, -3, 1): 2,
 (-1, -2, -3): 6,
 (-1, -2, -2): 34,
 (-1, -2, -1): 66,
 (-1, -2, 0): 49,
 (-1, -2, 1): 15,
 (-1, -2, 2): 1,
 (-1, -1, -3): 5,
 (-1, -1, -2): 42,
 (-1, -1, -1): 103,
 (-1, -1, 0): 101,
 (-1, -1, 1)

In [22]:
Tijk_basis(BGG, i,j,k)

{(-3, -3, -2): [],
 (-3, -3, -1): [],
 (-3, -3, 0): [],
 (-3, -2, -2): [],
 (-3, -2, -1): [],
 (-3, -2, 0): [],
 (-3, -2, 1): [ 1 -1],
 (-3, -1, -2): [],
 (-3, -1, -1): [],
 (-3, -1, 0): [ 1  0  0  0 -1 -1  1],
 (-3, -1, 1): [ 1 -1 -1],
 (-3, 0, -1): [ 1 -1],
 (-3, 0, 0): [ 1 -1 -1],
 (-3, 0, 1): [ 1 -1],
 (-2, -3, -3): [],
 (-2, -3, -2): [],
 (-2, -3, -1): [],
 (-2, -3, 0): [ 1 -1  0  1  0  1],
 (-2, -3, 1): [ 1 -1],
 (-2, -2, -3): [],
 (-2, -2, -2): [],
 (-2,
  -2,
  -1): [ 1  0  0  0  0  0  0 -1  0  0 -1  0  0 -1  0  1  0  0  0  0  0  1  1  0  0 -1  0  0  0  0  0  0  0  0],
 (-2,
  -2,
  0): [ 1  0  0  0  0  0 -1  0  1  0 -1  0  0  0  0  0  0 -1  1 -1  0  0  0  1  0 -1  1  0 -1  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0 -1  0 -1  0  0  0  0  0  0  0  0 -1  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0 -1  0  0 -1  0  2  0  0  0  0  0 -1  0  0  2  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  1  0  0  0  0  0  2 -1 -1 -1  0 -1  0  0  2 -1  0 -1  0]
 [ 0  0  0  0  1  0  0  0  

In [25]:
BGG = BGGComplex('A2')
s = 0
i = 0
j = 2
k = s-i-j
print(i+j,j-i,k)
display(Mijk(BGG,i,j,k).components)
cohom = BGGCohomology(BGG, Mijk(BGG,i,j,k), coker=Tijk_basis(BGG, i,j,k))
cohom.cohomology_LaTeX()

(2, 2, -2)


[[('u', 1, 'sym'), ('g', 0, 'wedge'), ('n', 2, 'wedge')],
 [('u', 0, 'sym'), ('g', 1, 'wedge'), ('n', 1, 'wedge')]]

<IPython.core.display.Math object>

In [26]:
BGG = BGGComplex('A2')
factory = FastModuleFactory(BGG.LA)
factory.weight_dic

{0: array([-1, -1], dtype=int32),
 1: array([-1,  0], dtype=int32),
 2: array([ 0, -1], dtype=int32),
 3: array([0, 0], dtype=int32),
 4: array([0, 0], dtype=int32),
 5: array([1, 1], dtype=int32),
 6: array([0, 1], dtype=int32),
 7: array([1, 0], dtype=int32)}

In [27]:
module =  Mijk(BGG,0,2,-2)
for mu, cl in module.weight_components.items():
    print(mu)
    print('-'*10)
    for c in cl:
        print(c)
    print('\n')

(0, 1)
----------
(1, array([[5, 1]], dtype=int32))


(-1, 1)
----------
(1, array([[6, 1]], dtype=int32))


(0, 0)
----------
(0, array([[5, 1, 2]], dtype=int32))
(1, array([[5, 0],
       [6, 2],
       [7, 1]], dtype=int32))


(-2, 0)
----------
(0, array([[6, 0, 1]], dtype=int32))
(1, array([[1, 1]], dtype=int32))


(-1, -2)
----------
(1, array([[0, 2],
       [2, 0]], dtype=int32))


(-1, -1)
----------
(0, array([[6, 0, 2],
       [7, 0, 1]], dtype=int32))
(1, array([[1, 2],
       [2, 1],
       [3, 0],
       [4, 0]], dtype=int32))


(-2, -2)
----------
(1, array([[0, 0]], dtype=int32))


(-2, -1)
----------
(1, array([[0, 1],
       [1, 0]], dtype=int32))


(0, -2)
----------
(0, array([[7, 0, 2]], dtype=int32))
(1, array([[2, 2]], dtype=int32))


(0, -1)
----------
(0, array([[5, 0, 2],
       [7, 1, 2]], dtype=int32))
(1, array([[3, 2],
       [4, 2],
       [7, 0]], dtype=int32))


(1, 0)
----------
(1, array([[5, 2]], dtype=int32))


(1, -1)
----------
(1, array([[7, 2]],

In [28]:
BGG.display_maps((0,0))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [29]:
cohom = BGGCohomology(BGG, Mijk(BGG,i,j,k))
cohom.weight_set.get_vertex_weights((0,0))

{'': (0, 0),
 '1': (-1, 0),
 '12': (-2, -1),
 '121': (-2, -2),
 '2': (0, -1),
 '21': (-1, -2)}

In [30]:
Mijk(BGG,0,1,-2).components

[[('u', 0, 'sym'), ('g', 0, 'wedge'), ('n', 1, 'wedge')]]

In [31]:
component_dic = {'b':factory.build_component('b','coad',subset=[]),'g':factory.build_component('g','coad',subset=[])
                ,'u':factory.build_component('u','coad',subset=[]),'n':factory.build_component('n','coad',subset=[])}

components = [[('b',1,'sym'),('n',1,'wedge')]]

module = FastLieAlgebraCompositeModule(factory,components,component_dic)
module.weight_components
for mu, cl in module.weight_components.items():
    print(mu)
    print('-'*10)
    print(cl[0][1])
    print('\n')

(0, -2)
----------
[[2 2]]


(-2, 0)
----------
[[1 1]]


(-2, -2)
----------
[[0 0]]


(-1, -1)
----------
[[1 2]
 [2 1]
 [3 0]
 [4 0]]


(-1, -2)
----------
[[0 2]
 [2 0]]


(-2, -1)
----------
[[0 1]
 [1 0]]


(0, -1)
----------
[[3 2]
 [4 2]]


(-1, 0)
----------
[[3 1]
 [4 1]]




In [32]:
compute_phi(BGG)

{0: [],
 1: array([[ 0,  6, -1]]),
 2: array([[0, 7, 1]]),
 3: array([[ 2,  6,  2],
        [ 1,  7, -1],
        [ 0,  5,  1]]),
 4: array([[ 1,  7,  2],
        [ 2,  6, -1],
        [ 0,  5,  1]])}

In [33]:
coadu=factory.coadjoint_action_tensor(factory.basis['b'],factory.basis['u'])
coadn=factory.coadjoint_action_tensor(factory.basis['b'],factory.basis['n'])
coadg=factory.coadjoint_action_tensor(factory.basis['b'],factory.g_basis)

In [34]:
coadg[(2,7)]

{}