Suppose we have an equivariant map of $\mathfrak b$ modules $L\colon M\to N$. Such maps automatically respect the weight decomposition, and we can consider $\ker L$ and $\operatorname{coker} L$ as $\mathfrak b$-modules. 

In both cases we need an (integer) basis for the ker / coker. For the kernel the action is easy to define, for the coker not so much. But maybe it's OK with the Smith normal form or whatnot.

In [25]:
import numpy as np

L = matrix(ZZ,[[1,2,3,0],[1,2,4,0],[1,2,2,0]])
L.smith_form()

(
                       [ 3 -2  0 -2]
[1 0 0 0]  [ 2 -1  0]  [ 0  0  0  1]
[0 1 0 0]  [ 1  0  0]  [-1  1  0  0]
[0 0 0 0], [-2  1  1], [ 0  0  1  0]
)

In [34]:
matrix(ZZ,[[1,0,2,0],[1,0,3,0],[2,0,1,0],[1,0,0,0]]).transpose().smith_form()

(
[1 0 0 0]  [0 0 1 0]  [-1  3 -3 -5]
[0 1 0 0]  [1 0 0 0]  [ 1 -2  2  3]
[0 0 0 0]  [0 1 0 0]  [ 0  0  0  1]
[0 0 0 0], [0 0 0 1], [ 0  0  1  0]
)

In [20]:
ck = L.smith_form()[-1][L.rank():]
ck

[-1  1  0]

Free module of degree 3 and rank 1 over Integer Ring
Echelon basis matrix:
[ 2 -1  0]