In [1]:
import sys
sys.path.append('../bggcomplex')

from bggcomplex import BGGComplex
from fast_module import FastLieAlgebraCompositeModule, FastModuleFactory, BGGCohomology

In [2]:
BGG = BGGComplex('A3')
f_factory = FastModuleFactory(BGG.LA)
component_dic = {'b':f_factory.build_component('n','coad')}
components = [[("b",2,'sym')],[("b",2,'wedge')]]

module1 = FastLieAlgebraCompositeModule(f_factory.weight_dic, components, component_dic)
cohom1 = BGGCohomology(BGG, module1)

components = [[("b",1,'sym'),("b",1,'sym')]]

module2 = FastLieAlgebraCompositeModule(f_factory.weight_dic, components, component_dic)
cohom2 = BGGCohomology(BGG, module2)

cohom1.cohomology_LaTeX(2,complex_string=r'G/B,\,\mathfrak u^{2}')
cohom2.cohomology_LaTeX(2,complex_string=r'G/B,\,\mathfrak u^{2}')

components = [[("b",2,'sym')]]

module3 = FastLieAlgebraCompositeModule(f_factory.weight_dic, components, component_dic)
cohom3 = BGGCohomology(BGG, module3)
cohom3.cohomology_LaTeX(2,complex_string=r'G/B,\,\mathfrak u^{2}')

[[         0 2866232286]]
[8 8]
[2375100798]
[array([ 8, 11], dtype=uint16)]
++++++++++
(array([[         0, 2866232286]]), array([1]), ('21', '121'), PBW[-alpha[1]])
----------
[]
[8 8]
[2375100798]
[array([ 8, 11], dtype=uint16)]
++++++++++
[[         0 1635429470]]
[6 6]
[1759699390]
[array([ 6, 11], dtype=uint16)]
++++++++++
(array([[         0, 1635429470]]), array([-1]), ('23', '232'), PBW[-alpha[3]])
----------
[]
[6 6]
[1759699390]
[array([ 6, 11], dtype=uint16)]
++++++++++
[[         0 2866232286]]
[8 8]
[2108647998]
[array([5, 8], dtype=uint16)]
++++++++++
(array([[         0, 2866232286]]), array([-1]), ('12', '121'), PBW[-alpha[2]])
----------
[]
[8 8]
[2108647998]
[array([5, 8], dtype=uint16)]
++++++++++
[[         0 1635429470]]
[6 6]
[1838437278]
[array([ 6, 12], dtype=uint16)]
++++++++++
(array([[         0, 1635429470]]), array([1]), ('32', '232'), PBW[-alpha[2]])
----------
[]
[6 6]
[1838437278]
[array([ 6, 12], dtype=uint16)]
++++++++++
[(array([2866232286]), array([

../bggcomplex/fast_module.py:197: RuntimeWarning: overflow encountered in int_scalars
  hash_modifier = column_hash_modifier*(self.pow_array[new_index] - self.pow_array[old_index])


<IPython.core.display.Math object>

[[          0 -1318710768]
 [          1  2976256528]]
uknown hash
[8 8]
[ 651405936 2485125040]
[array([ 8, 11], dtype=uint16), array([11,  8], dtype=uint16)]
++++++++++
(array([[          0, -1318710768],
       [          1,  2976256528]]), array([1, 1]), ('21', '121'), PBW[-alpha[1]])
----------
[[         0 -509981168]
 [         1 -509981168]]
[6 6]
[6 6]
[  36004528 -385711248]
[array([ 6, 11], dtype=uint16), array([11,  6], dtype=uint16)]
++++++++++
(array([[         0, -509981168],
       [         1, -509981168]]), array([-1, -1]), ('23', '232'), PBW[-alpha[3]])
----------
[[          0  2976256528]
 [          1 -1318710768]]
[8 8]
uknown hash
[2218672240 -559374928]
[array([5, 8], dtype=uint16), array([8, 5], dtype=uint16)]
++++++++++
(array([[          0,  2976256528],
       [          1, -1318710768]]), array([-1, -1]), ('12', '121'), PBW[-alpha[2]])
----------
[[         0 -509981168]
 [         1 -509981168]]
[6 6]
[6 6]
[ 791081680 -306973360]
[array([ 6, 12], dtype=u

<IPython.core.display.Math object>

[[         0 2866232286]]
[8 8]
[2375100798]
[array([ 8, 11], dtype=uint16)]
++++++++++
(array([[         0, 2866232286]]), array([1]), ('21', '121'), PBW[-alpha[1]])
----------
[[         0 1635429470]]
[6 6]
[1759699390]
[array([ 6, 11], dtype=uint16)]
++++++++++
(array([[         0, 1635429470]]), array([-1]), ('23', '232'), PBW[-alpha[3]])
----------
[[         0 2866232286]]
[8 8]
[2108647998]
[array([5, 8], dtype=uint16)]
++++++++++
(array([[         0, 2866232286]]), array([-1]), ('12', '121'), PBW[-alpha[2]])
----------
[[         0 1635429470]]
[6 6]
[1838437278]
[array([ 6, 12], dtype=uint16)]
++++++++++
(array([[         0, 1635429470]]), array([1]), ('32', '232'), PBW[-alpha[2]])
----------
[(array([2866232286]), array([-1])), (array([1635429470]), array([1])), (array([2866232286]), array([1])), (array([1635429470]), array([-1]))]
----------
[(array([1], dtype=uint32), array([-1])), (array([0], dtype=uint32), array([1])), (array([1], dtype=uint32), array([1])), (array([0], 

<IPython.core.display.Math object>

In [3]:
cohom2.compute_differential((0,0,0),2)

[[          0 -1318710768]
 [          1  2976256528]]
uknown hash
[8 8]
[ 651405936 2485125040]
[array([ 8, 11], dtype=uint16), array([11,  8], dtype=uint16)]
++++++++++
(array([[          0, -1318710768],
       [          1,  2976256528]]), array([1, 1]), ('21', '121'), PBW[-alpha[1]])
----------
[[         0 -509981168]
 [         1 -509981168]]
[6 6]
[6 6]
[  36004528 -385711248]
[array([ 6, 11], dtype=uint16), array([11,  6], dtype=uint16)]
++++++++++
(array([[         0, -509981168],
       [         1, -509981168]]), array([-1, -1]), ('23', '232'), PBW[-alpha[3]])
----------
[[          0  2976256528]
 [          1 -1318710768]]
[8 8]
uknown hash
[2218672240 -559374928]
[array([5, 8], dtype=uint16), array([8, 5], dtype=uint16)]
++++++++++
(array([[          0,  2976256528],
       [          1, -1318710768]]), array([-1, -1]), ('12', '121'), PBW[-alpha[2]])
----------
[[         0 -509981168]
 [         1 -509981168]]
[6 6]
[6 6]
[ 791081680 -306973360]
[array([ 6, 12], dtype=u

(
[-1  0  0]    
[ 0 -1  0]    
[ 0  0  1]    
[ 0  0  1]    
[ 0  1  0]    
[ 1  0  0]    
[ 0  0 -1]    
[ 0  0 -1], 10
)

In [16]:
import numpy as np

In [18]:
np.log2(2976256528+1318710768)

32.0

In [19]:
np.log2(2976256528)

31.470851733833957

In [4]:
column = BGG.column[3]
vertex_weights = cohom2.weight_set.get_vertex_weights((0,0,0))
for w in column:
    lbda = vertex_weights[w]
    if lbda in module2.weight_components:
        print(module2.get_hash(module2.weight_components[lbda][0]))

[-509981168]
[2976256528]


So for $u\otimes u$ it somehow created something with the hash -1318710768, which shouldn't even exist in the first place. We should figure out what this guy is. Let's check if it occurs in the complex at all somewhere, not just in deg 3.

The answer is NO. So that's interesting, but still hard to debug. We shouldn't have gone with this stupid hash system in the first place, but ah well.

In [5]:
hash_dic = module2.hash_dic
print(hash_dic[651405936])
print(hash_dic[-559374928])

[ 8 11]
[8 5]


In [6]:
cohom3.compute_differential((0,0,0),2)

[[         0 2866232286]]
[8 8]
[2375100798]
[array([ 8, 11], dtype=uint16)]
++++++++++
(array([[         0, 2866232286]]), array([1]), ('21', '121'), PBW[-alpha[1]])
----------
[[         0 1635429470]]
[6 6]
[1759699390]
[array([ 6, 11], dtype=uint16)]
++++++++++
(array([[         0, 1635429470]]), array([-1]), ('23', '232'), PBW[-alpha[3]])
----------
[[         0 2866232286]]
[8 8]
[2108647998]
[array([5, 8], dtype=uint16)]
++++++++++
(array([[         0, 2866232286]]), array([-1]), ('12', '121'), PBW[-alpha[2]])
----------
[[         0 1635429470]]
[6 6]
[1838437278]
[array([ 6, 12], dtype=uint16)]
++++++++++
(array([[         0, 1635429470]]), array([1]), ('32', '232'), PBW[-alpha[2]])
----------
[(array([2866232286]), array([-1])), (array([1635429470]), array([1])), (array([2866232286]), array([1])), (array([1635429470]), array([-1]))]
----------
[(array([1], dtype=uint32), array([-1])), (array([0], dtype=uint32), array([1])), (array([1], dtype=uint32), array([1])), (array([0], 

(
[ 0 -1]   
[ 1  0]   
[ 0  1]   
[-1  0], 5
)

In [7]:
cohom3.weight_module.weight_components

{(-2, -2, -2): [(0, array([[13, 13]], dtype=uint16))],
 (-2, -2, -1): [(0, array([[ 8, 13]], dtype=uint16))],
 (-2, -2, 0): [(0, array([[8, 8]], dtype=uint16))],
 (-2, -1, -1): [(0, array([[ 5, 13]], dtype=uint16))],
 (-2, -1, 0): [(0, array([[5, 8]], dtype=uint16))],
 (-2, 0, 0): [(0, array([[5, 5]], dtype=uint16))],
 (-1, -2, -2): [(0, array([[ 6, 13]], dtype=uint16))],
 (-1, -2, -1): [(0, array([[ 6,  8],
          [11, 13]], dtype=uint16))],
 (-1, -2, 0): [(0, array([[ 8, 11]], dtype=uint16))],
 (-1, -1, -2): [(0, array([[12, 13]], dtype=uint16))],
 (-1, -1, -1): [(0, array([[ 5,  6],
          [ 8, 12]], dtype=uint16))],
 (-1, -1, 0): [(0, array([[ 5, 11]], dtype=uint16))],
 (-1, 0, -1): [(0, array([[ 5, 12]], dtype=uint16))],
 (0, -2, -2): [(0, array([[6, 6]], dtype=uint16))],
 (0, -2, -1): [(0, array([[ 6, 11]], dtype=uint16))],
 (0, -2, 0): [(0, array([[11, 11]], dtype=uint16))],
 (0, -1, -2): [(0, array([[ 6, 12]], dtype=uint16))],
 (0, -1, -1): [(0, array([[11, 12]], dtype=ui

In [8]:
[[module3.get_hash(mod) for mod in mods] for mods in module3.weight_components.values()]

[[array([1493246590, 2453838686])],
 [array([1838437278])],
 [array([1883969310])],
 [array([1962707198])],
 [array([1617516510])],
 [array([1759699390])],
 [array([1696254398])],
 [array([757221694])],
 [array([2866232286])],
 [array([1635429470])],
 [array([-362594])],
 [array([2041445086])],
 [array([2250830878,  266090206])],
 [array([2108647998])],
 [array([1351063710])],
 [array([2375100798])],
 [array([141820286])],
 [array([-1351788898])],
 [array([344828094])]]

In [9]:
display(module2.component_primes)

[array([    7919, 62710561], dtype=int32)]

In [10]:
module2.components

[[('b', 1, 'sym'), ('b', 1, 'sym')]]

In [11]:
comp_type = [s[1] for s in module3.components[0]]
print(comp_type)
comp_primes = []
for i, n in enumerate(comp_type):
    comp_primes += [i + 1] * n
print(comp_primes)

[2]
[1, 1]


In [12]:
[[module2.get_hash(mod) for mod in mods] for mods in module2.weight_components.values()]

[[array([ -652164048, -1174776336,  1406483088,  2563862928])],
 [array([ 791081680, -306973360])],
 [array([160274448])],
 [array([915351600, 239012336])],
 [array([ -106178352, -1050506416])],
 [array([  36004528, -385711248])],
 [array([ 648898800, -971768528])],
 [array([554225328, 867245936])],
 [array([2976256528])],
 [array([-509981168])],
 [array([ -203358960, -2668385520])],
 [array([994089488])],
 [array([ 2360855120,   105420240,    63093840, -1457604656])],
 [array([2218672240, -559374928])],
 [array([-1316959216])],
 [array([ 651405936, 2485125040])],
 [array([  -61176080, -2003590352])],
 [array([-1554785264])],
 [array([ 141831728, -702527504])]]