In [1]:
import sys
sys.path.append('../bggcomplex')

from bggcomplex import BGGComplex
from fast_module import FastLieAlgebraCompositeModule, FastModuleFactory, BGGCohomology
import numpy as np

In [16]:
d = 'G2'
BGG = BGGComplex(d)
factory = FastModuleFactory(BGG.LA)
component_dic = {'u':factory.build_component('u','coad',subset=[])}
u_dim = len(component_dic['u'].basis)
print('dim of u is %d for root system %s' % (u_dim, d))
for k in range(u_dim+1):
    components = [[('u',k,'wedge')]]
    module = FastLieAlgebraCompositeModule(factory,components,component_dic)

    cohom = BGGCohomology(BGG, module)

    cohom.cohomology_LaTeX(complex_string=r'X_{'+d+r'},\wedge^{'+str(k)+'}T_X')

dim of u is 6 for root system G2


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [3]:
sorted(cohom.cohomology(0),key=lambda t:(sum(t[0]),t[0][::-1]))

[((1, 1, 1), 1),
 ((1, 2, 1), 2),
 ((2, 2, 1), 1),
 ((1, 2, 2), 1),
 ((3, 2, 1), 1),
 ((2, 2, 2), 1),
 ((1, 2, 3), 1),
 ((2, 3, 2), 1)]

In [4]:
mu = [1,1,1]
ws = cohom.weight_set
mu = ws.tuple_to_weight(mu)
mu

(1, 0, 0, -1)

In [5]:
mu+ws.rho

(4, 2, 1, -1)

In [6]:
pos_roots = [ws.tuple_to_weight(w) for w in BGG.neg_roots]
numerator = 1
denomenator = 1
for alpha in pos_roots:
    numerator*=(mu+ws.rho).dot_product(alpha)
    denomenator*=(ws.rho.dot_product(alpha))
dim = numerator/denomenator
dim

15

In [7]:
type(cohom.weight_set.rho)

sage.combinat.root_system.type_A.AmbientSpace_with_category.element_class

In [8]:
BGG.neg_roots

[array([0, 0, 1]),
 array([0, 1, 0]),
 array([1, 0, 0]),
 array([0, 1, 1]),
 array([1, 1, 0]),
 array([1, 1, 1])]